/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TyresRouteImport } from './routes/tyres'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfitLossRouteImport } from './routes/profit-loss'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EmiRouteImport } from './routes/emi'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DieselRouteImport } from './routes/diesel'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TyresRoute = TyresRouteImport.update({
  id: '/tyres',
  path: '/tyres',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitLossRoute = ProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiRoute = EmiRouteImport.update({
  id: '/emi',
  path: '/emi',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DieselRoute = DieselRouteImport.update({
  id: '/diesel',
  path: '/diesel',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diesel': typeof DieselRoute
  '/drivers': typeof DriversRoute
  '/emi': typeof EmiRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRoute
  '/garage': typeof GarageRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/profit-loss': typeof ProfitLossRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/tyres': typeof TyresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diesel': typeof DieselRoute
  '/drivers': typeof DriversRoute
  '/emi': typeof EmiRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRoute
  '/garage': typeof GarageRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/profit-loss': typeof ProfitLossRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/tyres': typeof TyresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/diesel': typeof DieselRoute
  '/drivers': typeof DriversRoute
  '/emi': typeof EmiRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRoute
  '/garage': typeof GarageRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/profit-loss': typeof ProfitLossRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trips': typeof TripsRoute
  '/tyres': typeof TyresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/diesel'
    | '/drivers'
    | '/emi'
    | '/expenses'
    | '/fleet'
    | '/garage'
    | '/maintenance'
    | '/notifications'
    | '/profit-loss'
    | '/reports'
    | '/settings'
    | '/trips'
    | '/tyres'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/diesel'
    | '/drivers'
    | '/emi'
    | '/expenses'
    | '/fleet'
    | '/garage'
    | '/maintenance'
    | '/notifications'
    | '/profit-loss'
    | '/reports'
    | '/settings'
    | '/trips'
    | '/tyres'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/diesel'
    | '/drivers'
    | '/emi'
    | '/expenses'
    | '/fleet'
    | '/garage'
    | '/maintenance'
    | '/notifications'
    | '/profit-loss'
    | '/reports'
    | '/settings'
    | '/trips'
    | '/tyres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DieselRoute: typeof DieselRoute
  DriversRoute: typeof DriversRoute
  EmiRoute: typeof EmiRoute
  ExpensesRoute: typeof ExpensesRoute
  FleetRoute: typeof FleetRoute
  GarageRoute: typeof GarageRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfitLossRoute: typeof ProfitLossRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TripsRoute: typeof TripsRoute
  TyresRoute: typeof TyresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tyres': {
      id: '/tyres'
      path: '/tyres'
      fullPath: '/tyres'
      preLoaderRoute: typeof TyresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit-loss': {
      id: '/profit-loss'
      path: '/profit-loss'
      fullPath: '/profit-loss'
      preLoaderRoute: typeof ProfitLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi': {
      id: '/emi'
      path: '/emi'
      fullPath: '/emi'
      preLoaderRoute: typeof EmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diesel': {
      id: '/diesel'
      path: '/diesel'
      fullPath: '/diesel'
      preLoaderRoute: typeof DieselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DieselRoute: DieselRoute,
  DriversRoute: DriversRoute,
  EmiRoute: EmiRoute,
  ExpensesRoute: ExpensesRoute,
  FleetRoute: FleetRoute,
  GarageRoute: GarageRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotificationsRoute: NotificationsRoute,
  ProfitLossRoute: ProfitLossRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TripsRoute: TripsRoute,
  TyresRoute: TyresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
